---
# connection block
- name: Test playbook to run
  hosts: all
  user: ec2-user
  become: true
  become_method: sudo 
  tasks:
  - name: Remove telnet
    ansible.builtin.package:      # module from the internet 
      name: telnet
      state: absent   # absent  # latest 

# ansible-playbook  -i ../setup/inventory   playbook.yaml 