---
# connection block
- name: Test playbook to run
  hosts: all
  user: ec2-user
  become: true
  become_method: sudo 
  tasks:
  - name: install multiple package
    ansible.builtin.package:      # module from the internet 
      name: 
      - telnet
      - elinks 
      - lftp
      - unzip
      state: present   # absent  # latest 


  # CMND + ]
  - name: Add the user 'johnd' with a specific uid and a primary group of 'admin'
    ansible.builtin.user:
      name: johnd
      comment: John Doe
      uid: 1040



# ansible-playbook  -i ../setup/inventory   playbook.yaml 