---
# connection block
- name: Test playbook to run
  hosts: all
  user: ec2-user
  become: true
  become_method: sudo 
  tasks:
  - name: install multiple package
    ansible.builtin.yum:      # module from the internet 
      name: httpd
      state: present  




# ansible-playbook -i ../setup/inventory   conditional_playbook.yaml 