---
# connection block
- name: Test playbook to run
  hosts: all
  user: ec2-user
  become: true
  become_method: sudo 
  tasks:
  - name: Create a file with a content
    ansible.builtin.lineinfile:      # module from the internet 
      path: /tmp/testfile
      line: 192.168.1.99 foo.lab.net foo
      create: yes




# ansible-playbook -i ../setup/inventory   lineinfile.yaml





  # - name: Print all available facts
  #   ansible.builtin.debug:
  #     var: ansible_facts['python']['version']['major']

