---
# connection block
- name: Test playbook to run
  hosts: all
  user: ec2-user
  become: true
  become_method: sudo 
  tasks:
  - name: Create a file with a content
    when: ansible_facts['distribution'] == "Ubuntu"
    ansible.builtin.lineinfile:      # module from the internet 
      path: /tmp/testfile
      regexp: '^192.168.1.99 foo.lab.net foo'           # Search for line that startswith '192'
      line: '172.16.1.99 foo.lab.net foo'





# ansible-playbook -i ../setup/inventory   lineinfile.yaml





  # - name: Print all available facts
  #   ansible.builtin.debug:
  #     var: ansible_facts['python']['version']['major']

