---
# connection block
- name: Test playbook to run
  hosts: all
  user: ec2-user
  become: true
  become_method: sudo 
  tasks:
  - name: install multiple package on ubuntu
    when: ansible_facts['distribution'] == "Ubuntu"
    ansible.builtin.apt:      # module from the internet 
      name: "*"
      state: latest  




# ansible-playbook -i ../setup/inventory   update_ubuntu.yaml 





  # - name: Print all available facts
  #   ansible.builtin.debug:
  #     var: ansible_facts['python']['version']['major']

