---
# connection block
- name: Installing wordpress
  hosts: all
  user: ec2-user
  become: true
  become_method: sudo 
  tasks:
  - name: install multiple package on amazon
    when: ansible_facts['distribution'] == "Amazon"
    ansible.builtin.package:      # module from the internet 
      name: 
      - httpd
      - php 
      - php-mysql 
      - telnet 
      - wget 
      state: present  

  - name: Download wordpress
    ansible.builtin.get_url:
      url: https://wordpress.org/wordpress-4.0.32.tar.gz
      dest: /tmp/

  - name: Extract wordpress.tgz into /tmp
    ansible.builtin.unarchive:
      src: /tmp/wordpress-4.0.32.tar.gz
      dest: /tmp/
      remote_src: true

  - name: Host Wordpress
    shell: "cp -r /tmp/wordpress/* /var/www/html/"
    ignore_errors: true


  - name: Start web server
    systemd: 
      name: httpd 
      state: restarted
      enabled: true


# ansible-playbook -i ../setup/inventory   wordpress.yaml